//go:build !ignore_autogenerated

/*
Copyright 2026 Arron Atchison.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LongContextInstance) DeepCopyInto(out *LongContextInstance) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LongContextInstance.
func (in *LongContextInstance) DeepCopy() *LongContextInstance {
	if in == nil {
		return nil
	}
	out := new(LongContextInstance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LongContextInstance) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LongContextInstanceList) DeepCopyInto(out *LongContextInstanceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LongContextInstance, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LongContextInstanceList.
func (in *LongContextInstanceList) DeepCopy() *LongContextInstanceList {
	if in == nil {
		return nil
	}
	out := new(LongContextInstanceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LongContextInstanceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LongContextInstanceSpec) DeepCopyInto(out *LongContextInstanceSpec) {
	*out = *in
	if in.PresetRef != nil {
		in, out := &in.PresetRef, &out.PresetRef
		*out = new(LongContextPresetReference)
		**out = **in
	}
	if in.Overrides != nil {
		in, out := &in.Overrides, &out.Overrides
		*out = new(LongContextOverrides)
		(*in).DeepCopyInto(*out)
	}
	in.HFToken.DeepCopyInto(&out.HFToken)
	if in.NodePort != nil {
		in, out := &in.NodePort, &out.NodePort
		*out = new(int32)
		**out = **in
	}
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LongContextInstanceSpec.
func (in *LongContextInstanceSpec) DeepCopy() *LongContextInstanceSpec {
	if in == nil {
		return nil
	}
	out := new(LongContextInstanceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LongContextInstanceStatus) DeepCopyInto(out *LongContextInstanceStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LongContextInstanceStatus.
func (in *LongContextInstanceStatus) DeepCopy() *LongContextInstanceStatus {
	if in == nil {
		return nil
	}
	out := new(LongContextInstanceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LongContextOverrides) DeepCopyInto(out *LongContextOverrides) {
	*out = *in
	if in.ModelID != nil {
		in, out := &in.ModelID, &out.ModelID
		*out = new(string)
		**out = **in
	}
	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = new(string)
		**out = **in
	}
	if in.ImagePullPolicy != nil {
		in, out := &in.ImagePullPolicy, &out.ImagePullPolicy
		*out = new(string)
		**out = **in
	}
	if in.MIGResource != nil {
		in, out := &in.MIGResource, &out.MIGResource
		*out = new(string)
		**out = **in
	}
	if in.MIGResourceCount != nil {
		in, out := &in.MIGResourceCount, &out.MIGResourceCount
		*out = new(int32)
		**out = **in
	}
	if in.Quantization != nil {
		in, out := &in.Quantization, &out.Quantization
		*out = new(string)
		**out = **in
	}
	if in.DType != nil {
		in, out := &in.DType, &out.DType
		*out = new(string)
		**out = **in
	}
	if in.MaxModelLen != nil {
		in, out := &in.MaxModelLen, &out.MaxModelLen
		*out = new(int32)
		**out = **in
	}
	if in.GPUMemoryUtilization != nil {
		in, out := &in.GPUMemoryUtilization, &out.GPUMemoryUtilization
		*out = new(string)
		**out = **in
	}
	if in.TensorParallelSize != nil {
		in, out := &in.TensorParallelSize, &out.TensorParallelSize
		*out = new(int32)
		**out = **in
	}
	if in.EnableAutoToolChoice != nil {
		in, out := &in.EnableAutoToolChoice, &out.EnableAutoToolChoice
		*out = new(bool)
		**out = **in
	}
	if in.ToolCallParser != nil {
		in, out := &in.ToolCallParser, &out.ToolCallParser
		*out = new(string)
		**out = **in
	}
	if in.SHMSizeLimit != nil {
		in, out := &in.SHMSizeLimit, &out.SHMSizeLimit
		*out = new(string)
		**out = **in
	}
	if in.ProgressDeadlineSeconds != nil {
		in, out := &in.ProgressDeadlineSeconds, &out.ProgressDeadlineSeconds
		*out = new(int32)
		**out = **in
	}
	if in.LivenessProbe != nil {
		in, out := &in.LivenessProbe, &out.LivenessProbe
		*out = new(ProbeConfig)
		**out = **in
	}
	if in.ReadinessProbe != nil {
		in, out := &in.ReadinessProbe, &out.ReadinessProbe
		*out = new(ProbeConfig)
		**out = **in
	}
	if in.KVCacheDtype != nil {
		in, out := &in.KVCacheDtype, &out.KVCacheDtype
		*out = new(string)
		**out = **in
	}
	if in.EnablePrefixCaching != nil {
		in, out := &in.EnablePrefixCaching, &out.EnablePrefixCaching
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LongContextOverrides.
func (in *LongContextOverrides) DeepCopy() *LongContextOverrides {
	if in == nil {
		return nil
	}
	out := new(LongContextOverrides)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LongContextPreset) DeepCopyInto(out *LongContextPreset) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LongContextPreset.
func (in *LongContextPreset) DeepCopy() *LongContextPreset {
	if in == nil {
		return nil
	}
	out := new(LongContextPreset)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LongContextPreset) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LongContextPresetList) DeepCopyInto(out *LongContextPresetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LongContextPreset, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LongContextPresetList.
func (in *LongContextPresetList) DeepCopy() *LongContextPresetList {
	if in == nil {
		return nil
	}
	out := new(LongContextPresetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LongContextPresetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LongContextPresetReference) DeepCopyInto(out *LongContextPresetReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LongContextPresetReference.
func (in *LongContextPresetReference) DeepCopy() *LongContextPresetReference {
	if in == nil {
		return nil
	}
	out := new(LongContextPresetReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LongContextPresetSpec) DeepCopyInto(out *LongContextPresetSpec) {
	*out = *in
	out.LivenessProbe = in.LivenessProbe
	out.ReadinessProbe = in.ReadinessProbe
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LongContextPresetSpec.
func (in *LongContextPresetSpec) DeepCopy() *LongContextPresetSpec {
	if in == nil {
		return nil
	}
	out := new(LongContextPresetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelConfigOverrides) DeepCopyInto(out *ModelConfigOverrides) {
	*out = *in
	if in.ModelID != nil {
		in, out := &in.ModelID, &out.ModelID
		*out = new(string)
		**out = **in
	}
	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = new(string)
		**out = **in
	}
	if in.ImagePullPolicy != nil {
		in, out := &in.ImagePullPolicy, &out.ImagePullPolicy
		*out = new(string)
		**out = **in
	}
	if in.MIGResource != nil {
		in, out := &in.MIGResource, &out.MIGResource
		*out = new(string)
		**out = **in
	}
	if in.MIGResourceCount != nil {
		in, out := &in.MIGResourceCount, &out.MIGResourceCount
		*out = new(int32)
		**out = **in
	}
	if in.Quantization != nil {
		in, out := &in.Quantization, &out.Quantization
		*out = new(string)
		**out = **in
	}
	if in.DType != nil {
		in, out := &in.DType, &out.DType
		*out = new(string)
		**out = **in
	}
	if in.MaxModelLen != nil {
		in, out := &in.MaxModelLen, &out.MaxModelLen
		*out = new(int32)
		**out = **in
	}
	if in.GPUMemoryUtilization != nil {
		in, out := &in.GPUMemoryUtilization, &out.GPUMemoryUtilization
		*out = new(string)
		**out = **in
	}
	if in.TensorParallelSize != nil {
		in, out := &in.TensorParallelSize, &out.TensorParallelSize
		*out = new(int32)
		**out = **in
	}
	if in.EnableAutoToolChoice != nil {
		in, out := &in.EnableAutoToolChoice, &out.EnableAutoToolChoice
		*out = new(bool)
		**out = **in
	}
	if in.ToolCallParser != nil {
		in, out := &in.ToolCallParser, &out.ToolCallParser
		*out = new(string)
		**out = **in
	}
	if in.SHMSizeLimit != nil {
		in, out := &in.SHMSizeLimit, &out.SHMSizeLimit
		*out = new(string)
		**out = **in
	}
	if in.ProgressDeadlineSeconds != nil {
		in, out := &in.ProgressDeadlineSeconds, &out.ProgressDeadlineSeconds
		*out = new(int32)
		**out = **in
	}
	if in.LivenessProbe != nil {
		in, out := &in.LivenessProbe, &out.LivenessProbe
		*out = new(ProbeConfig)
		**out = **in
	}
	if in.ReadinessProbe != nil {
		in, out := &in.ReadinessProbe, &out.ReadinessProbe
		*out = new(ProbeConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelConfigOverrides.
func (in *ModelConfigOverrides) DeepCopy() *ModelConfigOverrides {
	if in == nil {
		return nil
	}
	out := new(ModelConfigOverrides)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelPreset) DeepCopyInto(out *ModelPreset) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelPreset.
func (in *ModelPreset) DeepCopy() *ModelPreset {
	if in == nil {
		return nil
	}
	out := new(ModelPreset)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ModelPreset) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelPresetList) DeepCopyInto(out *ModelPresetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ModelPreset, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelPresetList.
func (in *ModelPresetList) DeepCopy() *ModelPresetList {
	if in == nil {
		return nil
	}
	out := new(ModelPresetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ModelPresetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelPresetSpec) DeepCopyInto(out *ModelPresetSpec) {
	*out = *in
	out.LivenessProbe = in.LivenessProbe
	out.ReadinessProbe = in.ReadinessProbe
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelPresetSpec.
func (in *ModelPresetSpec) DeepCopy() *ModelPresetSpec {
	if in == nil {
		return nil
	}
	out := new(ModelPresetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PresetReference) DeepCopyInto(out *PresetReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PresetReference.
func (in *PresetReference) DeepCopy() *PresetReference {
	if in == nil {
		return nil
	}
	out := new(PresetReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProbeConfig) DeepCopyInto(out *ProbeConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProbeConfig.
func (in *ProbeConfig) DeepCopy() *ProbeConfig {
	if in == nil {
		return nil
	}
	out := new(ProbeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VLLMInstance) DeepCopyInto(out *VLLMInstance) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VLLMInstance.
func (in *VLLMInstance) DeepCopy() *VLLMInstance {
	if in == nil {
		return nil
	}
	out := new(VLLMInstance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VLLMInstance) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VLLMInstanceList) DeepCopyInto(out *VLLMInstanceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VLLMInstance, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VLLMInstanceList.
func (in *VLLMInstanceList) DeepCopy() *VLLMInstanceList {
	if in == nil {
		return nil
	}
	out := new(VLLMInstanceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VLLMInstanceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VLLMInstanceSpec) DeepCopyInto(out *VLLMInstanceSpec) {
	*out = *in
	if in.PresetRef != nil {
		in, out := &in.PresetRef, &out.PresetRef
		*out = new(PresetReference)
		**out = **in
	}
	if in.Overrides != nil {
		in, out := &in.Overrides, &out.Overrides
		*out = new(ModelConfigOverrides)
		(*in).DeepCopyInto(*out)
	}
	in.HFToken.DeepCopyInto(&out.HFToken)
	if in.NodePort != nil {
		in, out := &in.NodePort, &out.NodePort
		*out = new(int32)
		**out = **in
	}
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VLLMInstanceSpec.
func (in *VLLMInstanceSpec) DeepCopy() *VLLMInstanceSpec {
	if in == nil {
		return nil
	}
	out := new(VLLMInstanceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VLLMInstanceStatus) DeepCopyInto(out *VLLMInstanceStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VLLMInstanceStatus.
func (in *VLLMInstanceStatus) DeepCopy() *VLLMInstanceStatus {
	if in == nil {
		return nil
	}
	out := new(VLLMInstanceStatus)
	in.DeepCopyInto(out)
	return out
}
