// Code generated by controller-gen. DO NOT EDIT.
// (This file is hand-written to bootstrap the module; `make generate` regenerates it.)

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// --- ProbeConfig ---

func (in *ProbeConfig) DeepCopyInto(out *ProbeConfig) {
	*out = *in
}

func (in *ProbeConfig) DeepCopy() *ProbeConfig {
	if in == nil {
		return nil
	}
	out := new(ProbeConfig)
	in.DeepCopyInto(out)
	return out
}

// --- ModelPreset ---

func (in *ModelPresetSpec) DeepCopyInto(out *ModelPresetSpec) {
	*out = *in
	in.LivenessProbe.DeepCopyInto(&out.LivenessProbe)
	in.ReadinessProbe.DeepCopyInto(&out.ReadinessProbe)
}

func (in *ModelPresetSpec) DeepCopy() *ModelPresetSpec {
	if in == nil {
		return nil
	}
	out := new(ModelPresetSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *ModelPreset) DeepCopyInto(out *ModelPreset) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

func (in *ModelPreset) DeepCopy() *ModelPreset {
	if in == nil {
		return nil
	}
	out := new(ModelPreset)
	in.DeepCopyInto(out)
	return out
}

func (in *ModelPreset) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *ModelPresetList) DeepCopyInto(out *ModelPresetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		items := make([]ModelPreset, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&items[i])
		}
		out.Items = items
	}
}

func (in *ModelPresetList) DeepCopy() *ModelPresetList {
	if in == nil {
		return nil
	}
	out := new(ModelPresetList)
	in.DeepCopyInto(out)
	return out
}

func (in *ModelPresetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// --- VLLMInstance ---

func (in *PresetReference) DeepCopyInto(out *PresetReference) {
	*out = *in
}

func (in *PresetReference) DeepCopy() *PresetReference {
	if in == nil {
		return nil
	}
	out := new(PresetReference)
	in.DeepCopyInto(out)
	return out
}

func (in *ModelConfigOverrides) DeepCopyInto(out *ModelConfigOverrides) {
	*out = *in
	if in.ModelID != nil {
		v := *in.ModelID
		out.ModelID = &v
	}
	if in.Image != nil {
		v := *in.Image
		out.Image = &v
	}
	if in.ImagePullPolicy != nil {
		v := *in.ImagePullPolicy
		out.ImagePullPolicy = &v
	}
	if in.MIGResource != nil {
		v := *in.MIGResource
		out.MIGResource = &v
	}
	if in.MIGResourceCount != nil {
		v := *in.MIGResourceCount
		out.MIGResourceCount = &v
	}
	if in.Quantization != nil {
		v := *in.Quantization
		out.Quantization = &v
	}
	if in.DType != nil {
		v := *in.DType
		out.DType = &v
	}
	if in.MaxModelLen != nil {
		v := *in.MaxModelLen
		out.MaxModelLen = &v
	}
	if in.GPUMemoryUtilization != nil {
		v := *in.GPUMemoryUtilization
		out.GPUMemoryUtilization = &v
	}
	if in.TensorParallelSize != nil {
		v := *in.TensorParallelSize
		out.TensorParallelSize = &v
	}
	if in.EnableAutoToolChoice != nil {
		v := *in.EnableAutoToolChoice
		out.EnableAutoToolChoice = &v
	}
	if in.ToolCallParser != nil {
		v := *in.ToolCallParser
		out.ToolCallParser = &v
	}
	if in.SHMSizeLimit != nil {
		v := *in.SHMSizeLimit
		out.SHMSizeLimit = &v
	}
	if in.ProgressDeadlineSeconds != nil {
		v := *in.ProgressDeadlineSeconds
		out.ProgressDeadlineSeconds = &v
	}
	if in.LivenessProbe != nil {
		out.LivenessProbe = in.LivenessProbe.DeepCopy()
	}
	if in.ReadinessProbe != nil {
		out.ReadinessProbe = in.ReadinessProbe.DeepCopy()
	}
}

func (in *ModelConfigOverrides) DeepCopy() *ModelConfigOverrides {
	if in == nil {
		return nil
	}
	out := new(ModelConfigOverrides)
	in.DeepCopyInto(out)
	return out
}

func (in *VLLMInstanceSpec) DeepCopyInto(out *VLLMInstanceSpec) {
	*out = *in
	if in.PresetRef != nil {
		out.PresetRef = in.PresetRef.DeepCopy()
	}
	if in.Overrides != nil {
		out.Overrides = in.Overrides.DeepCopy()
	}
	in.HFToken.DeepCopyInto(&out.HFToken)
	if in.Replicas != nil {
		v := *in.Replicas
		out.Replicas = &v
	}
}

func (in *VLLMInstanceSpec) DeepCopy() *VLLMInstanceSpec {
	if in == nil {
		return nil
	}
	out := new(VLLMInstanceSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *VLLMInstanceStatus) DeepCopyInto(out *VLLMInstanceStatus) {
	*out = *in
	if in.Conditions != nil {
		conds := make([]metav1.Condition, len(in.Conditions))
		for i := range in.Conditions {
			in.Conditions[i].DeepCopyInto(&conds[i])
		}
		out.Conditions = conds
	}
}

func (in *VLLMInstanceStatus) DeepCopy() *VLLMInstanceStatus {
	if in == nil {
		return nil
	}
	out := new(VLLMInstanceStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *VLLMInstance) DeepCopyInto(out *VLLMInstance) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *VLLMInstance) DeepCopy() *VLLMInstance {
	if in == nil {
		return nil
	}
	out := new(VLLMInstance)
	in.DeepCopyInto(out)
	return out
}

func (in *VLLMInstance) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *VLLMInstanceList) DeepCopyInto(out *VLLMInstanceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		items := make([]VLLMInstance, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&items[i])
		}
		out.Items = items
	}
}

func (in *VLLMInstanceList) DeepCopy() *VLLMInstanceList {
	if in == nil {
		return nil
	}
	out := new(VLLMInstanceList)
	in.DeepCopyInto(out)
	return out
}

func (in *VLLMInstanceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
