---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vllm-operator-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - nodes
  - persistentvolumeclaims
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
  - patch
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - patch
  - watch
- apiGroups:
  - discovery.k8s.io
  resources:
  - endpointslices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - vllm.aatchison.io
  resources:
  - longcontextinstances
  - vllminstances
  verbs:
  - get
  - list
  - patch
  - watch
- apiGroups:
  - vllm.aatchison.io
  resources:
  - longcontextinstances/status
  - vllminstances/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - vllm.aatchison.io
  resources:
  - longcontextpresets
  - modelpresets
  verbs:
  - get
  - list
  - watch
